### ISSUE TITLE
TypeError: can't dump anonymous class Class

### ISSUE THREAD

**Issue by ChunAllen** [ddnexus/flex#25]
I'm using 
elasticsearch 1.3.0, 
gem "flex-rails",  
gem "patron",
rails 4.1.2,
rbx. 2.2.7(rubinius)

Here's my code:
**app/model/retailer.rb**

```
class Retailer < ActiveRecord::Base
  include Flex::ModelIndexer
  flex.sync self

  def flex_source
    {
      name: name
    }
  end
end
```

**app/model/retailer_flex.rb**

```
class RetailerFlex

  include Flex::ActiveModel
  flex.type = "retailer"
  attribute :name

end
```

and in my **config/initializers/flex.rb**

```
  config.flex_models = %w[ Retailer ]
  config.flex_active_models = %w[ RetailerFlex ]
```

but when I import flex using:

```
$ rake flex:import
```

I'm getting 

```
rake aborted
TypeError: can't dump anonymous class Class
```

**Comment by ddnexus** [comment]
Please, run it with --trace. Besides, it could be useful to see what you
have in Retailer and in RetailerFlex. Thanks.

**Comment by ddnexus** [comment]
Oh.... sorry, I didn't see you posted the relevant part of the classes :).

**Comment by ChunAllen** [comment]
@ddnexus here's the result from rake flex:index:create --trace

```
$ rake flex:index:create --trace
** Invoke flex:index:create (first_time)
** Invoke environment (first_time)
** Execute environment
** Execute flex:index:create
rake aborted!
TypeError: can't dump anonymous class Class
/Users/allenchun/.rvm/rubies/rbx-2.2.7/gems/gems/rubysl-yaml-2.0.4/lib/syck/rubytypes.rb:6:in `to_yaml'
rubyext.c:in `node_export'
rubyext.c:in `add'
/Users/allenchun/.rvm/rubies/rbx-2.2.7/gems/gems/rubysl-yaml-2.0.4/lib/syck/rubytypes.rb:115:in `to_yaml'
kernel/bootstrap/array.rb:76:in `each'
/Users/allenchun/.rvm/rubies/rbx-2.2.7/gems/gems/rubysl-yaml-2.0.4/lib/syck/rubytypes.rb:114:in `to_yaml'
rubyext.c:in `seq'
/Users/allenchun/.rvm/rubies/rbx-2.2.7/gems/gems/rubysl-yaml-2.0.4/lib/syck/rubytypes.rb:113:in `to_yaml'
rubyext.c:in `emit'
/Users/allenchun/.rvm/rubies/rbx-2.2.7/gems/gems/rubysl-yaml-2.0.4/lib/syck.rb:409:in `quick_emit'
/Users/allenchun/.rvm/rubies/rbx-2.2.7/gems/gems/rubysl-yaml-2.0.4/lib/syck/rubytypes.rb:112:in `to_yaml'
rubyext.c:in `node_export'
rubyext.c:in `add'
```

**Comment by ChunAllen** [comment]
@ddnexus I'm using rubinius and rails 4.1.2
my .ruby-version 

```
rbx-2.2.7
```

**Comment by ddnexus** [comment]
Not very useful/complete trace. What I see is limited to the last calls all inside the syck lib.

**Comment by ChunAllen** [comment]
Thanks @ddnexus I found out that the flex-rails gem is not working with rubinius

**Comment by ddnexus** [comment]
How did you find out? It looks like an issue with syck, and may be due to how you setup the models, or even to a flex bug.
